<?php
use Restserver\Libraries\REST_Controller;
defined('BASEPATH') OR exit('No direct script access allowed');

// This can be removed if you use __autoload() in config.php OR use Modular Extensions
/** @noinspection PhpIncludeInspection */
//To Solve File REST_Controller not found
require APPPATH . 'libraries/REST_Controller.php';
require APPPATH . 'libraries/Format.php';
require APPPATH . 'libraries/ImplementJwt.php';

/**
 * This is an example of a few basic user interaction methods you could use
 * all done with a hardcoded array
 *
 * @package         CodeIgniter
 * @subpackage      Rest Server
 * @category        Controller
 * @author          Phil Sturgeon, Chris Kacerguis
 * @license         MIT
 * @link            https://github.com/chriskacerguis/codeigniter-restserver
 */
class User extends CI_Controller {
    use REST_Controller {
        REST_Controller::__construct as private __resTraitConstruct;
    }

    function __construct()
    {
        // Construct the parent class
        parent::__construct();

        $this->load->model("user_model");
        $this->load->model("auth_model");
        $this->load->model("curriculum_model");
        $this->load->model("helper_model");
        $this->load->model("dashboard_model");

        $this->__resTraitConstruct();
        $this->objOfJwt = new ImplementJwt();
        header('Content-Type: application/json');
        // Configure limits on our controller methods
        // Ensure you have created the 'limits' table and enabled 'limits' within application/config/rest.php
        $this->methods['users_get']['limit'] = 500; // 500 requests per hour per user/key
        $this->methods['users_post']['limit'] = 100; // 100 requests per hour per user/key
        $this->methods['users_delete']['limit'] = 50; // 50 requests per hour per user/key
    }

    public function login_post(){
        $message = [
            'id' => 100, // Automatically generated by the model
            'name' => $this->post('descriptive_title'),
            'email' => $this->post('subject_code'),
            'message' => 'Added a resource'
        ];

        $this->set_response($message, 200); // CREATED (201) being the HTTP response code
    }

    //fetch
    public function logged_user_post(){
        $input = $this->post();

        $response = $this->db->join('roles', 'ON users.role_id = roles.role_id', 'left')->get_where('users', array('username' => $input['username']))->row_array();

        $this->set_response($response, 200);
    }

    // public function users_get(){
    //     $query = $this->db->get_where('users', array('role_id !=' => 6 ))->result_array();
    //     $i = 0;
    //     foreach ($query as $row) {
    //         $role = $this->user_model->role($row['role_id']);
    //         $designation = $this->user_model->designation($row['designation_id']);

    //         $query[$i]['user_id'] = (int)$query[$i]['user_id'];
    //         $query[$i]['role_id'] = (int)$query[$i]['role_id'];
    //         $query[$i]['designation_id'] =  (int)$query[$i]['designation_id'];
    //         $query[$i]['department_id'] = (int)$query[$i]['department_id'];
    //         $query[$i]['job_status_id'] = (int)$query[$i]['job_status_id'];

    //         $query[$i]['role'] = $role;
    //         $query[$i]['designation'] = $designation;
    //         $query[$i]['fullname'] = $query[$i]['firstname'] ." ". $query[$i]['lastname'];
    //         // unset($query[$i]['password']);
    //         $i++;
    //     }

    //     $this->set_response($query, 200); // CREATED (201) being the HTTP response code
    // }

    public function feeds_get(){
        $query = $this->db->get('feeds')->result_array();
        $this->set_response($query, 200);
    }

    public function feed_types_get(){
        $query = $this->db->get('feed_types')->result_array();
        $this->set_response($query, 200);
    }

    public function users_get(){
        $query = $this->db->get_where('users', array('role_id !=' => 1 ))->result_array();
        $this->set_response($query, 200);
    }

    public function trainings_get(){
        $query = $this->db->get('trainings')->result_array();
        $this->set_response($query, 200);
    }

    public function pending_users_get(){
        $query = $this->db->get_where('users', array('user_status' => 'Pending' ))->result_array();
        $this->set_response($query, 200);
    }

    public function active_users_get(){
        $query = $this->db->get_where('users', array('user_status' => 'Active','role_id !=' => 1 ))->result_array();
        $this->set_response($query, 200);
    }

    public function disapproved_users_get(){
        $query = $this->db->get_where('users', array('user_status' => 'Disapproved','role_id !=' => 1 ))->result_array();
        $this->set_response($query, 200);
    }

    public function workers_post(){
        $input = $this->post();
        $query = $this->db->get_where('users', $input)->result_array();

        $i = 0;
        foreach ($query as $row) {
            $query2 = $this->db->get_where('jobs', array('service_worker_id' => $row['user_id'], 'job_status' => 'Completed' ))->result_array();

            $sum = 0;
            $average = 0;

            foreach ($query2 as $row2) {
                $sum = $sum + $row2['rate'];
            }

            if ($sum != 0) {
                $average = $sum / count($query2);
            }

            $query[$i]['average'] = $average;
            $query[$i]['experience_points'] = $average*count($query2);
            $i++;
        }

        $this->set_response($query, 200);
    }

    public function user_post(){
        $input = $this->post();

        $query = $this->db->join('roles', 'ON users.role_id = roles.role_id')->get_where('users', $input)->row_array();

        $this->set_response($query, 200);
    }

    public function pig_post(){
        $input = $this->post();

        $query = $this->db->get_where('pigs', $input)->row_array();

        $this->set_response($query, 200);
    }

    public function training_post(){
        $input = $this->post();

        $query = $this->db->get_where('trainings', $input)->row_array();

        $this->set_response($query, 200);
    }

    public function pigs_post(){
        $input = $this->post();

        $query = $this->db->get_where('pigs', $input)->result_array();

        $this->set_response($query, 200);
    }

    public function requested_job_post(){
        $input = $this->post();

        $query = $this->db->join('users', 'ON jobs.service_worker_id = users.user_id')->join('roles', 'ON users.role_id = roles.role_id')->get_where('jobs', $input)->row_array();

        $this->set_response($query, 200);
    }

    public function job_offers_post(){
        $input = $this->post();

        $query = $this->db->order_by('date_added', 'DESC')->join('users', 'ON jobs.service_seeker_id = users.user_id')->join('roles', 'ON users.role_id = roles.role_id')->get_where('jobs', $input)->result_array();

        $this->set_response($query, 200);
    }

    public function job_offer_post(){
        $input = $this->post();

        $query = $this->db->join('users', 'ON jobs.service_seeker_id = users.user_id')->join('roles', 'ON users.role_id = roles.role_id')->get_where('jobs', $input)->row_array();

        $this->set_response($query, 200);
    }

    public function quality_logs_post(){
        $input = $this->post();

        $query = $this->db->get_where('feed_quality_logs', $input)->result_array();

        $this->set_response($query, 200);
    }

    public function nutritional_logs_post(){
        $input = $this->post();

        $query = $this->db->get_where('nutritional_logs', $input)->result_array();

        $this->set_response($query, 200);
    }

    public function messages_post(){
        $input = $this->post();

        $query = $this->db->get_where('messages', $input)->result_array();

        $i = 0;
        foreach ($query as $row) {
            $query[$i]['sender'] = $this->db->get_where('users', array('user_id' => $row['sender_id']))->row_array();
            $query[$i]['recipient'] = $this->db->get_where('users', array('user_id' => $row['recipient_id']))->row_array();

            $i = $i+1;
        }

        $this->set_response($query, 200);
    }

    public function average_rating_post(){
        $input = $this->post();

        $query = $this->db->get_where('jobs', $input)->result_array();

        $sum = 0;
        $average = 0;

        foreach ($query as $row) {
            $sum = $sum + $row['rate'];
        }

        if ($sum != 0) {
            $average = $sum / count($query);
        }

        $this->set_response(round($average, 1), 200);
    }

    public function average_rating2_post(){
        $input = $this->post();

        $query = $this->db->get_where('jobs', $input)->result_array();

        $sum = 0;
        $average = 0;

        foreach ($query as $row) {
            $sum = $sum + $row['rate2'];
        }

        if ($sum != 0) {
            $average = $sum / count($query);
        }

        $this->set_response(round($average, 1), 200);
    }

    public function apply_for_approval_post(){
        $input = $this->post();
        $data['user_status'] = 'Pending';
        $this->db->where($input)->update('users', $data);
         $response = array(
            'type' => 'success',
            'result' => 'Success',
            'message' => 'Request for Account Approval has been Sent!'
        );

        $this->set_response($response, 200);
    }

    public function edit_user_status_post(){
        $input = $this->post();

        $this->db->where(array('user_id' => $input['user_id'] ))->update('users', $input);
         $response = array(
            'type' => 'info',
            'result' => 'Success',
            'message' => 'User Status has been successfully updated into -'.$input['user_status'].'-'
        );

        $this->set_response($response, 200);
    }

    public function users_by_role_post(){
        $input = $this->post();

        $query = $this->db->get_where('users', $input)->result_array();

        $this->set_response($query, 200);
    }

    public function users_by_status_post(){
        $input = $this->post();

        $query = $this->db->get_where('users', $input)->result_array();

        $this->set_response($query, 200);
    }

    public function notifications_post(){
        $input = $this->post();

        $query = $this->db->get_where('notifications', $input)->result_array();

        $this->set_response($query, 200);
    }

    public function send_notification_post(){
        $input = $this->post();

        $i = 0;        
        foreach ($input as $row) {
            foreach ($row['contacts'] as $row2) {
                $data['user_id'] = $row2['user_id'];
                $data['subject'] = 'Subject for Contact Tracing !';
                $data['content'] = 'We would just like to inform you that you are being subjected for contact tracing. This is in regards to your travel on '.date('F j, Y' , strtotime($row2['log_time'])).' at '.$row['visiting_point_name'].' Please Cooperate to your Local Government Unit, or the Inter-Agency Task Force. Thank you and keep safe, God Bless us all !. This is a system generated message.';
                $data['date_sent'] = date('Y-m-d');

                $this->db->insert('notifications', $data);

                //Send email coresspondingly
                $data2['subject'] = $data['subject'];
                $data2['content'] = $data['content'];
                $this->user_model->send_email($row2, $data2);
            }
        }

        $response = array(
            'type' => 'success',
            'result' => 'Success',
            'message' => 'Notification Sent Successfully!'
        );

        $this->set_response($response, 200);
    }

    public function health_logs_post(){
        $input = $this->post();

        $query = $this->db->get_where('health_change_logs', $input)->result_array();

        $this->set_response($query, 200);
    }

    public function roles_get(){
        $query = $this->db->get('roles')->result_array();
        $this->set_response($query, 200);
    }

    public function certifications_post(){
        $input = $this->post();

        $query = $this->db->get_where('certifications', $input)->result_array();
        $this->set_response($query, 200);
    }

    //Add
    public function add_user_post(){
        $input = $this->post();

        $response = $this->user_model->insert_user($input);

        $this->set_response($response, 200);
    }

    public function add_pig_post(){
        $input = $this->post();

        $response = $this->user_model->insert_pig($input);

        $this->set_response($response, 200);
    }

    public function add_rate_post(){
        $input = $this->post();

        $response = $this->user_model->insert_rate($input);

        $this->set_response($response, 200);
    }

    public function add_feed_quality_post(){
        $input = $this->post();

        $feed = $this->db->get_where('feeds', array('feed_id'=> $input['feed_id']))->row_array();

        $log['user_id'] = $input['user_id'];
        $log['sender_id'] = $input['user_id'];
        $log['message'] = "Brand: ".$feed['feed_brand']."<br>Ingredients: ".$input['ingredients']."<br>Feed Formulation: ".$input['formulation'];
        $log['time_stamp'] = date('Y-m-d h:i:s');

        $this->db->insert('feed_quality_logs', $log);


        $log2['user_id'] = $input['user_id'];
        $log2['sender_id'] = 0;
        $log2['message'] = "Nutritional Content: ".$feed['nutritional_content']."<br>Storage Control Protocol: ".$feed['storage_protocol'];
        $log2['time_stamp'] = date('Y-m-d h:i:s');

        $this->db->insert('feed_quality_logs', $log2);

        $response = array(
            'type' => 'success',
            'result' => 'Success',
            'message' => 'Successfully sent query');

        $this->set_response($response, 200);
    }

    public function add_nutritional_post(){
        $input = $this->post();

        $feed = $this->db->get_where('feeds', array('feed_id'=> $input['feed_id']))->row_array();
        $feed_type = $this->db->get_where('feed_types', array('feed_type_id'=> $input['feed_type_id']))->row_array();
        $guides = $this->db->get('feeding_guides')->result_array();

        $log['user_id'] = $input['user_id'];
        $log['sender_id'] = $input['user_id'];
        $log['message'] = "Brand: ".$feed['feed_brand']."<br>Feed Type: ".$feed_type['feed_type_name']."<br>Nutritional Content: ".$input['nutritional_content']."<br>Age (in days): ".$input['age']." days"."<br>Weight: ".$input['weight']." kgs";
        $log['time_stamp'] = date('Y-m-d h:i:s');

        $this->db->insert('nutritional_logs', $log);


        $log2['user_id'] = $input['user_id'];
        $log2['sender_id'] = 0;

        if ($input['right'] == false) {
            $log2['message'] = $input['result']."<br>You can follow the feeding guide below.<br><br>".$guides[0]['guide']."<br>For further information, you can consult a nutritionist.<br>";
        } else {
            $log2['message'] = $input['result']."<br>For further information, you can consult a nutritionist.<br>";
        }
        
        $log2['time_stamp'] = date('Y-m-d h:i:s');

        $this->db->insert('nutritional_logs', $log2);

        $response = array(
            'type' => 'success',
            'result' => 'Success',
            'message' => 'Successfully sent query');

        $this->set_response($response, 200);
    }

    public function add_message_post(){
        $input = $this->post();

        $input['time_stamp'] = date('Y-m-d h:i:s');

        $this->db->insert('messages', $input);

        $response = array(
            'type' => 'success',
            'result' => 'Success',
            'message' => 'Successfully sent message');

        $this->set_response($response, 200);
    }

    public function submit_file_post(){
        $input = $this->post();

        $config['upload_path']          = './images/'.$input['destination'].'s/';
        $config['allowed_types']        = 'gif|jpg|png|jpeg|pdf';
        $config['max_size']             = 100000;


        // print_r($_FILES['file']);
        // print_r($input);

        $this->load->library('upload', $config);

        if ( ! $this->upload->do_upload('file'))
        {
            $error = array('error' => $this->upload->display_errors());
            
            $response = array(
                'result' => 'Failed',
                'message' => 'Failed to submit the File '.$input['destination'],
                'type' => 'danger',
                'extra' => $error 
            );

            $this->set_response($response, 400);
        }
        else
        {
            $data = array('upload_data' => $this->upload->data());

            $old_img = $this->db->get_where('users', array('user_id' => $input['user_id'] ))->row_array();

            if ($old_img[$input['destination']] != '') {
                if (file_exists ( './images/'.$input['destination'].'s/'.$old_img[$input['destination']] ) == true) {
                    unlink('./images/'.$input['destination'].'s/'.$old_img[$input['destination']]);
                }   
            }

            $data2 = array(
                $input['destination'] => $data['upload_data']['file_name'],
            );

            $this->db->where('user_id', $input['user_id'])->update('users', $data2);

            $response = array(
                'result' => 'Success',
                'message' => 'Successfully updated '.$input['destination'].' file',
                'type' => 'success' 
            );

            $this->set_response($response, 200);
        }
    }

    public function submit_file2_post(){
        $input = $this->post();

        $config['upload_path']          = './images/'.$input['destination'].'s/';
        $config['allowed_types']        = 'gif|jpg|png|jpeg|pdf';
        $config['max_size']             = 100000;


        // print_r($_FILES['file']);
        // print_r($input);

        $this->load->library('upload', $config);

        if ( ! $this->upload->do_upload('file'))
        {
            $error = array('error' => $this->upload->display_errors());
            
            $response = array(
                'result' => 'Failed',
                'message' => 'Failed to submit the File '.$input['destination'],
                'type' => 'danger',
                'extra' => $error 
            );

            $this->set_response($response, 400);
        }
        else
        {
            $data = array('upload_data' => $this->upload->data());

            $old_img = $this->db->get_where('pigs', array('pig_id' => $input['pig_id'] ))->row_array();

            if ($old_img[$input['destination']] != '') {
                if (file_exists ( './images/'.$input['destination'].'s/'.$old_img[$input['destination']] ) == true) {
                    unlink('./images/'.$input['destination'].'s/'.$old_img[$input['destination']]);
                }   
            }

            $data2 = array(
                $input['destination'] => $data['upload_data']['file_name'],
            );

            $this->db->where('pig_id', $input['pig_id'])->update('pigs', $data2);

            $response = array(
                'result' => 'Success',
                'message' => 'Successfully updated '.$input['destination'].' file',
                'type' => 'success' 
            );

            $this->set_response($response, 200);
        }
    }

    public function submit_file3_post(){
        $input = $this->post();

        $config['upload_path']          = './images/'.$input['destination'].'s/';
        $config['allowed_types']        = 'gif|jpg|png|jpeg|pdf';
        $config['max_size']             = 100000;


        // print_r($_FILES['file']);
        // print_r($input);

        $this->load->library('upload', $config);

        if ( ! $this->upload->do_upload('file'))
        {
            $error = array('error' => $this->upload->display_errors());
            
            $response = array(
                'result' => 'Failed',
                'message' => 'Failed to submit the File '.$input['destination'],
                'type' => 'danger',
                'extra' => $error 
            );

            $this->set_response($response, 400);
        }
        else
        {
            $data = array('upload_data' => $this->upload->data());

            $data2 = array(
                'title' => $input['title'],
                'description' => $input['description'],
                'date_added' => date('Y-m-d'),
                $input['destination'] => $data['upload_data']['file_name'],
            );

            $this->db->insert('trainings', $data2);

            $response = array(
                'result' => 'Success',
                'message' => 'Successfully added new Training Article ',
                'type' => 'success' 
            );

            $this->set_response($response, 200);
        }
    }

    public function submit_certification_post(){
        $input = $this->post();

        $config['upload_path']          = './images/'.$input['destination'].'s/';
        $config['allowed_types']        = 'gif|jpg|png|jpeg|pdf';
        $config['max_size']             = 100000;


        // print_r($_FILES['file']);
        // print_r($input);

        $this->load->library('upload', $config);

        if ( ! $this->upload->do_upload('file'))
        {
            $error = array('error' => $this->upload->display_errors());
            
            $response = array(
                'result' => 'Failed',
                'message' => 'Failed to submit the File '.$input['destination'],
                'type' => 'danger',
                'extra' => $error 
            );

            $this->set_response($response, 400);
        }
        else
        {
            $data = array('upload_data' => $this->upload->data());


            $data2 = array(
                'certification_path' => $data['upload_data']['file_name'],
                'certification_name' => $input['certification_name'],
                'certification_description' => $input['certification_description'],
                'date_acquired' => $input['date_acquired'],
                'date_added' => date('Y-m-d'),
                'user_id' => $input['user_id']
            );

            $this->db->insert('certifications', $data2);

            $response = array(
                'result' => 'Success',
                'message' => 'Successfully uploaded new certification file',
                'type' => 'success' 
            );

            $this->set_response($response, 200);
        }
    }

    //Edit
    public function edit_user_post(){
        $input = $this->post();
        
        $response = $this->user_model->update_user($input);

        $this->set_response($response, 200);
    }

    public function edit_pig_post(){
        $input = $this->post();
        
        $response = $this->user_model->update_pig($input);

        $this->set_response($response, 200);
    }

    public function edit_job_post(){
        $input = $this->post();
        
        $this->db->where('job_id', $input['job_id'])->update('jobs', $input);

        $response = array(
            'result' => 'Success',
            'message' => 'Successfully updated Jobs',
            'type' => 'success' 
        );

        $this->set_response($response, 200);
    }


    public function accept_post(){
        $input = $this->post();

        $input['job_status'] = 'On-going';

        $response = $this->user_model->accept($input);

        $this->set_response($response, 200);
    }

    public function reject_post(){
        $input = $this->post();
        
        $input['job_status'] = 'Rejected';

        $response = $this->user_model->reject($input);

        $this->set_response($response, 200);
    }

    public function pay_post(){
        $input = $this->post();

        $response = $this->user_model->pay($input);

        $this->set_response($response, 200);
    }

    public function submit_edit_health_status_post(){
        $input = $this->post();
        
        $this->db->where('user_id', $input['user_id'])->update('users', $input);
        $this->db->insert('health_change_logs', $input);

        if ($input['health_status'] == 'Positive') {
            $day = (int)date('d' , strtotime($input['date_changed']));
            $day = (int)$day + 1;
            $month = (int)date('m', strtotime($input['date_changed']));
            $year = (int)date('Y', strtotime($input['date_changed']));
            $start = date('Y-m-d' , strtotime($input['date_changed']));
            $end = date('Y-m-d' , strtotime($year.'-'.$month.'-'.$day));
            $sql = 'SELECT *
                FROM visit_logs
                LEFT JOIN users ON visit_logs.user_id = users.user_id
                LEFT JOIN visiting_points ON visit_logs.visiting_point_id = visiting_points.visiting_point_id
                WHERE visit_logs.user_id = '.$input['user_id'].' AND (visit_logs.log_time >= "'.$start.'" AND visit_logs.log_time < "'.$end.'")';

            $logs = $this->db->query($sql)->result_array();

            $i = 0;        
            foreach ($logs as $row) {
                //update positive count
                $count = $this->db->select('positive_count')->get_where('visiting_points', array('visiting_point_id' => $row['visiting_point_id'] ))->row_array();
                $count['positive_count'] = $count['positive_count'] +1;
                $this->db->where('visiting_point_id', $row['visiting_point_id'])->update('visiting_points', $count);
            }
        }

        $response = array(
            'result' => 'Success',
            'message' => 'Successfully changed Resident Health Status',
            'type' => 'success' 
        );

        $this->set_response($response, 200);
    }

    public function approve_user_post(){
        $input = $this->post();

        $this->db->where($input)->update('users', array('user_status' => 'Active' ));

        $message = array('user_id' => $input['user_id'],
                        'subject' => 'Registration Approved',
                        'content' => 'Your Registration has been examined by the Administrators, and has been approved. You can are now provided with QR code and can use the system.',
                        'date_sent' => date('Y-m-d')
         );

        $this->db->insert('notifications', $message);

        $response = array(
            'result' => 'Success',
            'message' => 'Successfully approved new user.',
            'type' => 'success' 
        );

        $this->set_response($response, 200);
    }

    public function decline_user_post(){
        $input = $this->post();

        $this->db->where($input)->update('users', array('user_status' => 'Declined' ));
        
        $message = array('user_id' => $input['user_id'],
                        'subject' => 'Registration Declined',
                        'content' => 'Your Registration has been examined by the Administrators, and has been declined or rejected. Please provide a clear photo of yourself and a valid ID and re-apply for registration approval.',
                        'date_sent' => date('Y-m-d')
         );

        $this->db->insert('notifications', $message);

        $response = array(
            'result' => 'Success',
            'message' => 'Successfully declined new user.',
            'type' => 'warning' 
        );

        $this->set_response($response, 200);
    }

    public function re_apply_post(){
        $input = $this->post();

        $this->db->where($input)->update('users', array('user_status' => 'Pending' ));

        $response = array(
            'result' => 'Success',
            'message' => 'Successfully Re-applied for registration.',
            'type' => 'success' 
        );

        $this->set_response($response, 200);
    }

    //Delete Data

    public function delete_data_post(){
        $input = $this->post();

        $response = $this->user_model->delete_data($input);

        $this->set_response($response, 200);
    }

    public function delete_user_post(){
        $input = $this->post();

        $account_sm = $this->db->get_where('account_statements', array('student_id' => $input['user_id'] ))->result_array();
        $transcripts = $this->db->get_where('transcripts', array('student_id' => $input['user_id'] ))->result_array();

        foreach ($account_sm as $row) {
            $this->db->where('account_sm_id', $row['account_sm_id'])->delete('enrolled_subjects');
            $this->db->where('account_sm_id', $row['account_sm_id'])->delete('receipts');
        }

        foreach ($transcripts as $row) {
            $this->db->where('transcript_id', $row['transcript_id'])->delete('credentials');
        }

        $this->db->where($input)->delete('users');

        $response = array(
            'result' => 'Success',
            'message' => 'Deleted student successfully',
            'type' => 'warning' 
        );

        $this->set_response($response, 200);
    }

    //Misc
    public function generate_sidebar_nav_post(){
        $input = $this->post();
        $input['role'] = (int)$input['role'];
        $count = 0;
        $i = 0;
        foreach ($input['items'] as $row) {
            if (isset($row['role'])) {
                foreach ($row['role'] as $row2) {
                    if ($row2 == $input['role']) {
                        $count++;
                    }
                }

                if ($count == 0) {
                    $input['items'][$i]['class'] = 'd-none';
                }

                $count = 0;
            }
            $i++;
        }

        $this->set_response($input['items'], 200);
    }

    public function swines_statistics_post(){
        $input = $this->post();
        $data['labels'] = ['Total Swines', 'Male', 'Female', 'Pregnant', 'Deceased'];
        $data['data'] = [];

        $total = $this->db->get_where('pigs', $input)->num_rows();
        $male = $this->db->get_where('pigs', array('user_id' => $input['user_id'], 'gender' => 'Male' ))->num_rows();
        $female = $this->db->get_where('pigs', array('user_id' => $input['user_id'], 'gender' => 'Female' ))->num_rows();
        $pregnant = $this->db->get_where('pigs', array('user_id' => $input['user_id'], 'maternity_status' => 'Pregnant' ))->num_rows();
        $deceased = $this->db->get_where('pigs', array('user_id' => $input['user_id'], 'life_status' => 'Deceased' ))->num_rows();


        array_push($data['data'], $total);
        array_push($data['data'], $male);
        array_push($data['data'], $female);
        array_push($data['data'], $pregnant);
        array_push($data['data'], $deceased);

        $this->set_response($data, 200);
    }

    public function users_statistics_get(){
        $data['labels'] = ['Total Users'];
        $data['data'] = [];

        $active = $this->db->get('users')->num_rows();

        array_push($data['data'], $active);

        $this->set_response($data, 200);
    }

    public function roles_statistics_get(){
        $data['labels'] = ['Service Worker', 'Service Finder'];
        $data['data'] = [];

        $service_worker = $this->db->get_where('users', array('role_id' => 2 ))->num_rows();
        $job_finder = $this->db->get_where('users', array('role_id' => 3 ))->num_rows();

        array_push($data['data'], $service_worker);
        array_push($data['data'], $job_finder);

        $this->set_response($data, 200);
    }

    public function common_jobs_get(){
        $data['labels'] = [];
        $data['data'] = [];

        $job_types = $this->db->get('job_types')->result_array();

        $i = 0;
        foreach ($job_types as $row) {
            array_push($data['labels'], $row['job_type_name']);

            $jobs = $this->db->get_where('jobs', array('job_type_id' => $row['job_type_id'], 'job_status' => 'Completed' ));
            array_push($data['data'], $jobs->num_rows());
            $i++;
        }

        $this->set_response($data, 200);
    }

    public function job_types_get(){
        $data = $this->db->get('job_types')->result_array();

        $this->set_response($data, 200);
    }

}
